const fs = require('fs');

const path = './data/locales/he.json';
const data = JSON.parse(fs.readFileSync(path, 'utf8'));

const notesMap = {
    "Agarwood": "אוד",
    "Agarwood (Oud)": "אוד",
    "Oud": "אוד",
    "Amberwood": "אמברווד",
    "Ambre gris": "אמברגריס",
    "Ambrette (Musk Mallow)": "אמברט",
    "Bergamot": "ברגמוט",
    "Bergamote": "ברגמוט",
    "Birch": "עץ שדר",
    "Black Pepper": "פלפל שחור",
    "Black Tea": "תה שחור",
    "Bois de cachemire": "עץ קשמיר",
    "Bois de santal": "אלגום (סנדלווד)",
    "Sandalwood": "אלגום (סנדלווד)",
    "Burnt Sugar": "סוכר שרוף",
    "Cade oil": "שמן קייד",
    "Cannelle": "קינמון",
    "Cappuccino": "קפוצ'ינו",
    "Caramel": "קרמל",
    "Cardamom": "הל",
    "Cassis": "קסיס",
    "Cedar": "ארז",
    "Cedar Bark": "קליפת עץ ארז",
    "Cèdre": "ארז",
    "Chinese Cedar": "ארז סיני",
    "Citron": "אתרוג / סיטרון (לימון)",
    "Coconut": "קוקוס",
    "Coconut Milk": "חלב קוקוס",
    "Coffee CO2": "קפה",
    "Coumarin": "קומרין",
    "Cuir": "עור",
    "Leather": "עור",
    "Cypriol": "ציפריול / נגרמותה",
    "Fig": "תאנה",
    "Floral Notes": "תווים פרחוניים",
    "Frankincense": "לבונה",
    "Gardenia": "גרדניה",
    "Géranium": "גרניום",
    "Ginger": "ג'ינג'ר",
    "Gurjan balsam": "גורג'ן בלזם",
    "Jasmin": "יסמין",
    "Jasmine": "יסמין",
    "Labdanum": "לאבדנום",
    "Lemon": "לימון",
    "Lily of the Valley": "שושנת העמקים",
    "Limoncello": "לימונצ'לו",
    "Lychee": "ליצ'י",
    "Macaron": "מקרון",
    "Magnolia": "מגנוליה",
    "Mandarin Orange": "מנדרינה",
    "Mango": "מנגו",
    "Milk": "חלב",
    "Mimosa": "מימוזה",
    "Mint": "מנטה",
    "Mung Beans": "שעועית מש",
    "Musc": "מאסק",
    "Musk": "מאסק",
    "Noix de muscade": "אגוז מוסקט",
    "Nutmeg": "אגוז מוסקט",
    "Oakmoss": "אזוב אלון (אוקמוס)",
    "Orange": "תפוז",
    "Orris": "איריס",
    "Osmanthus": "אוסמנטוס",
    "Passionfruit": "פסיפלורה",
    "Patchouli": "פצ'ולי",
    "Peach": "אפרסק",
    "Pink Pepper": "פלפל ורוד",
    "Precious Woods": "עצים יקרים",
    "Raspberry": "פטל",
    "Rhubarbe": "ריבס (רוברב)",
    "Rice": "אורז",
    "Rose": "ורד",
    "Rose de Mai": "ורד מאי",
    "Rosemary": "רוזמרין",
    "Rum": "רום",
    "Saffron": "זעפרן",
    "Safran": "זעפרן",
    "Salt": "מלח",
    "Sesame": "שומשום",
    "Spearmint": "ספירמינט (נענע)",
    "Sweet Orange": "תפוז מתוק",
    "Timbersilk™": "טימברסילק",
    "Tobacco": "טבק",
    "Tomato Leaf": "עלה עגבנייה",
    "Tonka Bean": "פולי טונקה",
    "Tuberose": "טוברוז",
    "Turkish Rose": "ורד טורקי",
    "Vanilla": "וניל",
    "Vanille": "וניל",
    "Verveine": "ורבנה",
    "Vetiver": "וטיבר",
    "Violet Leaf": "עלי סיגלית",
    "White Musk": "מאסק לבן",
    "White Peach": "אפרסק לבן",
    "Ylang-ylang": "אילנג-אילנג",
    "Ylang-Ylang": "אילנג-אילנג"
};

data.common.notes_map = { ...data.common.notes_map, ...notesMap };

fs.writeFileSync(path, JSON.stringify(data, null, 4));
console.log("he.json updated!");
