'use client';
// Force push check

import { useState, useEffect } from 'react';
import { toast } from 'react-hot-toast';
import { Loader2, Mail, CheckCircle2, XCircle, Search, Clock, Box } from 'lucide-react';
import Image from 'next/image';

export default function RecommendationsAdminPage() {
    const [items, setItems] = useState([]);
    const [loading, setLoading] = useState(true);
    const [processingId, setProcessingId] = useState(null);

    useEffect(() => {
        fetchRecommendations();
    }, []);

    const fetchRecommendations = async () => {
        try {
            const res = await fetch('/api/admin/recommendations');
            if (res.ok) {
                const data = await res.json();
                setItems(data);
            } else {
                toast.error('שגיאה בטעינת המלצות ממתינות');
            }
        } catch (error) {
            toast.error('שגיאת רשת');
        } finally {
            setLoading(false);
        }
    };

    const handleApprove = async (id) => {
        setProcessingId(id);
        const loadingToast = toast.loading('מעדכן המלצה...');
        try {
            const res = await fetch('/api/admin/recommendations', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ id })
            });

            if (res.ok) {
                toast.success('ההמלצה אושרה ותשלח במועד המתוכנן (30 יום מההזמנה)', { id: loadingToast });
                setItems(prev => prev.map(item => item.id === id ? { ...item, status: 'approved' } : item));
            } else {
                toast.error('שגיאה באישור ההמלצה', { id: loadingToast });
            }
        } catch (error) {
            toast.error('שגיאת רשת', { id: loadingToast });
        } finally {
            setProcessingId(null);
        }
    };

    const handleReject = async (id) => {
        toast((t) => (
            <div className="flex flex-col gap-3 p-1">
                <p className="font-bold text-sm text-gray-800">האם אתה בטוח שברצונך לדחות את שליחת המייל הזה?</p>
                <div className="text-xs text-gray-500 mb-1">זה יבטל את ההמלצה הנוכחית והמערכת תנסה למצוא המלצה חדשה ומתאימה יותר.</div>
                <div className="flex gap-2 justify-end">
                    <button
                        onClick={async () => {
                            toast.dismiss(t.id);
                            await executeReject(id);
                        }}
                        className="bg-red-600 text-white text-xs px-4 py-2 rounded-lg font-bold hover:bg-red-700 transition shadow-sm"
                    >
                        כן, דחה
                    </button>
                    <button
                        onClick={() => toast.dismiss(t.id)}
                        className="bg-gray-100 text-gray-700 text-xs px-4 py-2 rounded-lg font-bold hover:bg-gray-200 transition border"
                    >
                        ביטול
                    </button>
                </div>
            </div>
        ), { duration: 6000, position: 'top-center' });
    };

    const executeReject = async (id) => {
        setProcessingId(id);
        const loadingToast = toast.loading('מעדכן המלצות...');
        try {
            const res = await fetch(`/api/admin/recommendations?id=${id}`, {
                method: 'DELETE'
            });

            if (res.ok) {
                toast.success('ההמלצה נדחתה. מחפש המלצה חדשה...', { id: loadingToast });
                // Trigger fetch to get the NEW pending recommendation generated by the backend
                await fetchRecommendations();
            } else {
                toast.error('שגיאה בדחיית ההמלצה', { id: loadingToast });
            }
        } catch (error) {
            toast.error('שגיאת רשת', { id: loadingToast });
        } finally {
            setProcessingId(null);
        }
    };

    if (loading) {
        return (
            <div className="flex justify-center items-center h-64">
                <Loader2 className="w-8 h-8 animate-spin text-gray-500" />
            </div>
        );
    }

    const pendingItems = items.filter(i => i.status === 'pending');
    const approvedItems = items.filter(i => i.status === 'approved');

    const renderItemCard = (item, isPendingActionable) => {
        const originalItems = typeof item.original_items === 'string' ? JSON.parse(item.original_items) : item.original_items || [];
        const suggestedProducts = typeof item.suggested_products === 'string' ? JSON.parse(item.suggested_products) : item.suggested_products || [];
        const email = item.customer_details?.email || 'ללא אימייל';
        const firstName = item.customer_details?.first_name || 'לקוח';
        
        // Ensure date string exists and can be parsed
        let orderDateText = '';
        if (item.created_at) {
            orderDateText = new Date(item.created_at).toLocaleDateString('he-IL');
        }

        return (
            <div key={item.id} className="bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden transition-all hover:shadow-md">
                <div className="p-6 border-b border-gray-100 bg-gray-50/50 flex justify-between items-center">
                    <div className="flex flex-col">
                        <div className="flex items-center gap-2 mb-1">
                            <span className="font-bold text-lg text-gray-900">{firstName}</span>
                            <span className="bg-gray-200 text-gray-700 text-xs px-2 py-1 rounded-full font-medium tracking-wide">
                                הזמנה #{item.order_id}
                            </span>
                        </div>
                        <div className="text-gray-500 text-sm flex items-center gap-2">
                            <Mail className="w-4 h-4" />
                            {email}
                        </div>
                        {orderDateText && (
                            <div className="text-gray-400 text-xs mt-1 font-mono">
                                נוצר ב-{orderDateText} (יישלח לאחר 30 יום מההזמנה)
                            </div>
                        )}
                    </div>
                    <div className="flex gap-3">
                        {isPendingActionable ? (
                            <>
                                <button
                                    onClick={() => handleReject(item.id)}
                                    disabled={processingId === item.id}
                                    className="px-4 py-2 text-red-600 bg-red-50 hover:bg-red-100 rounded-lg flex items-center gap-2 transition-colors disabled:opacity-50 text-sm font-bold shadow-sm"
                                >
                                    <XCircle className="w-4 h-4" />
                                    דחה
                                </button>
                                <button
                                    onClick={() => handleApprove(item.id)}
                                    disabled={processingId === item.id || !email}
                                    className="px-6 py-2 bg-gradient-to-l from-indigo-600 to-indigo-700 hover:from-indigo-700 hover:to-indigo-800 text-white rounded-lg flex items-center gap-2 shadow-md transition-all disabled:opacity-50 text-sm font-bold"
                                >
                                    {processingId === item.id ? (
                                        <Loader2 className="w-4 h-4 animate-spin" />
                                    ) : (
                                        <CheckCircle2 className="w-4 h-4" />
                                    )}
                                    אשר (ימתין לתזמון 30 יום)
                                </button>
                            </>
                        ) : (
                            <div className="px-5 py-2 bg-emerald-50 text-emerald-600 rounded-lg flex items-center gap-2 font-bold text-sm">
                                <CheckCircle2 className="w-4 h-4" />
                                אושר להמתנה
                                <button
                                    onClick={() => handleReject(item.id)}
                                    disabled={processingId === item.id}
                                    className="mr-3 p-1.5 text-red-400 hover:bg-red-100 hover:text-red-600 rounded mr-2 transition-colors"
                                    title="בטל אישור (ימחק)"
                                >
                                    <XCircle className="w-4 h-4" />
                                </button>
                            </div>
                        )}
                    </div>
                </div>
                
                <div className="p-6 grid grid-cols-1 lg:grid-cols-2 gap-8">
                    {/* Original Order side */}
                    <div className="bg-gray-50 rounded-xl p-5 border border-gray-100">
                        <h3 className="font-bold text-gray-700 flex items-center gap-2 mb-4 border-b border-gray-200 pb-2">
                            <Box className="w-5 h-5 text-gray-500" />
                            הזמנה מקורית
                        </h3>
                        <ul className="space-y-3">
                            {originalItems.map((oi, idx) => (
                                <li key={idx} className="flex items-center justify-between text-sm py-1 border-b border-gray-50 last:border-0">
                                    <div className="flex flex-col flex-1 min-w-0">
                                        <span className="font-bold text-gray-900 truncate">{oi.brand_he || oi.brand}</span>
                                        <div className="flex items-center gap-1.5 text-xs text-gray-400" dir="rtl">
                                            <span className="truncate">{oi.model_he || oi.model}</span>
                                            <span className="opacity-30">|</span>
                                            <span className="whitespace-nowrap font-bold text-gray-500">{oi.size} מ"ל</span>
                                        </div>
                                    </div>
                                    <div className="flex items-center gap-4 shrink-0">
                                        <div className="flex flex-col items-end">
                                            <span className="text-[10px] text-gray-400 font-bold uppercase tracking-tighter">כמות</span>
                                            <span className="text-sm font-black text-gray-600">{oi.quantity}</span>
                                        </div>
                                        <div className="flex flex-col items-end min-w-[70px]">
                                            <span className="text-[10px] text-gray-400 font-bold uppercase tracking-tighter">מחיר</span>
                                            <span className="text-sm font-black text-indigo-600" dir="ltr">₪{oi.price?.toLocaleString()}</span>
                                        </div>
                                    </div>
                                </li>
                            ))}
                            {originalItems.length === 0 && (
                                <li className="text-gray-400 text-sm italic">לא נמצא פירוט פריטים להזמנה #{item.order_id}</li>
                            )}
                        </ul>
                    </div>

                    {/* Artificial Suggestions side */}
                    <div className="bg-indigo-50/30 rounded-xl p-5 border border-indigo-100">
                        <h3 className="font-bold text-indigo-900 flex items-center gap-2 mb-4 border-b border-indigo-100 pb-2">
                            <Search className="w-5 h-5 text-indigo-600" />
                            המלצות מותאמות לתבנית הריח
                        </h3>
                        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                            {suggestedProducts.map((p, idx) => (
                                <div key={idx} className="bg-white p-3 rounded-lg border border-indigo-100 shadow-sm text-center relative overflow-hidden group">
                                    {p.image_url ? (
                                        <div className="h-16 w-full flex justify-center items-center mb-2">
                                            <img src={p.image_url} alt={p.name} className="h-full object-contain group-hover:scale-105 transition-transform" />
                                        </div>
                                    ) : (
                                        <div className="h-16 w-full bg-gray-100 rounded mb-2 flex items-center justify-center">
                                            <Box className="text-gray-300 w-6 h-6" />
                                        </div>
                                    )}
                                    <div className="text-xs font-bold text-gray-900 truncate px-1" title={p.name}>{p.name}</div>
                                    <div className="text-[10px] text-gray-400 font-bold uppercase tracking-wider"><span dir="ltr">₪ {p.price?.toLocaleString()}</span></div>
                                    <div className="text-[10px] text-gray-500 truncate mt-1">{p.brand}</div>
                                    <div className="mt-2 text-[10px] bg-indigo-50 text-indigo-700 px-2 py-1 rounded inline-block truncate max-w-full">
                                        {p.notes || 'תווים דומים'}
                                    </div>
                                </div>
                            ))}
                            {suggestedProducts.length === 0 && (
                                <div className="text-indigo-400 text-sm italic col-span-full">לא נמצאו המלצות מספיק טובות</div>
                            )}
                        </div>
                    </div>
                </div>
            </div>
        );
    };

    return (
        <div className="p-6 max-w-6xl mx-auto" dir="rtl">
            <div className="flex items-center justify-between mb-8">
                <div>
                    <h1 className="text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-gray-900 to-gray-600">
                        אישור אימיילים להמלצות אישיות (AI)
                    </h1>
                    <p className="text-gray-500 mt-2 flex items-center">
                        <Mail className="w-4 h-4 ml-2" />
                        {pendingItems.length} מיילים ממתינים לאישור שלך (לשליחה בעתיד)
                    </p>
                </div>
            </div>

                {pendingItems.length === 0 ? (
                    <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-12 text-center">
                        <CheckCircle2 className="w-16 h-16 text-green-500 mx-auto mb-4" />
                        <h2 className="text-xl font-bold text-gray-900">הכל נקי!</h2>
                        <p className="text-gray-500 mt-2">אין כרגע המלצות שממתינות לאישור.</p>
                    </div>
                ) : (
                    <div className="flex flex-col gap-6">
                        {pendingItems.map((item) => renderItemCard(item, true))}
                    </div>
                )}

            {approvedItems.length > 0 && (
                <div className="mt-12">
                    <div className="flex items-center justify-between mb-6">
                        <div>
                            <h2 className="text-2xl font-bold text-gray-800">
                                אושרו בהמתנה לשליחה
                            </h2>
                            <p className="text-gray-500 mt-1 flex items-center">
                                <Clock className="w-4 h-4 ml-2" />
                                {approvedItems.length} מיילים ממתינים שיעברו 30 ימים מההזמנה שלהם
                            </p>
                        </div>
                    </div>
                    <div className="flex flex-col gap-6 opacity-75 grayscale hover:grayscale-0 transition-all">
                        {approvedItems.map((item) => renderItemCard(item, false))}
                    </div>
                </div>
            )}
        </div>
    );
}
